# backend/netlify.toml

[build]
base = "."
# publish = "build_output" # HAPUS BARIS INI ATAU KOMENTARI
command = "echo 'Netlify build for Python Functions starting...'"

[functions]
directory = "netlify/functions"

[functions.python]
version = "3.9"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true